# Run all the mocha tests on nodejs

name: Node.js CI

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: CI Tests for ${{matrix.package}} on Node.js ${{ matrix.node-version }} ğŸ§ª
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [v16.x, v18.x, v19.x, v20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        package: ["basic", "common", "rster", "types", "worker-express"]

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install â¤µï¸
        run: npm run packages:${{ matrix.package }}:ci

      - name: Cache â™»ï¸
        uses: actions/cache@v1.2.1
        with:
          path: /cache/ci/module_cache
          key: /cache/ci/module_cache

      - name: Run tests ğŸ”¬
        run: npm run packages:${{ matrix.package }}:test

      - name: Upload coverage reports to Codecov â˜ï¸
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build ${{matrix.package}} on Node.js v18.x ğŸ”¨
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ["basic", "common", "rster", "types", "worker-express"]

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js v18.x ğŸ“¦
        uses: actions/setup-node@v3
        with:
          node-version: v18.x
          cache: "npm"

      - name: Install â¤µï¸
        run: npm run packages:${{ matrix.package }}:ci

      - name: Cache â™»ï¸
        uses: actions/cache@v1.2.1
        with:
          path: /cache/ci/module_cache
          key: /cache/ci/module_cache

      - name: Build ğŸ”§
        run: npm run packages:${{ matrix.package }}:build
