name: Release Basic Package

on:
  push:
    tags:
      - "release/basic/v*"

jobs:
  build:
    name: Build ğŸ› ï¸
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Setup Node.js ğŸ“¦
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies ğŸ”ƒ
        run: npm run packages:basic:ci

      - name: Build ğŸ”¨
        run: npm run packages:basic:build

      - name: Test ğŸ§ª
        run: npm run packages:basic:test

  publish-npm:
    name: Publish to NPM Registry ğŸ“¦
    needs: draft-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Setup Node.js ğŸ“¦
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Publish â˜ï¸
        run: npm run packages:basic:publish:npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    name: Publish to GitHub Package Registry ğŸ“¦
    needs: draft-release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Setup Node.js ğŸ“¦
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Publish â˜ï¸
        run: npm run packages:basic:publish:gpr
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  draft-release:
    name: Draft Release for tag ğŸ“¦
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Setup Node.js ğŸ“¦
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Pack Release ğŸ“¦
        run: npm run packages:basic:pack
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Release â˜ï¸
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./packages/basic/*.tgz
            ./packages/basic/changelog.md
            ./packages/basic/README.md
            ./packages/basic/LICENSE
          tag_name: ${{github.ref}}
          body: |
            See changelog for details
          name: ${{github.ref_name}}
